### ISSUE TITLE
Node  13 module loading requires another entry point

### ISSUE THREAD

**Issue by ainthek** [simple-statistics/simple-statistics#448]
version 7.0.8.
running in node.js 13.

import { median, mean, mode } from "simple-statistics";
                 
SyntaxError: The requested module 'simple-statistics' does not provide an export named 'mean'

**Comment by tmcw** [comment]
simple-statistics currently has 5 module entry points, which meant that it worked with node, native browser imports, unpkg, rollup, browserify, and a few others. Node.js somehow invented _another_ entry point, and _another_ [complex system for exporting](https://nodejs.org/api/esm.html#esm_dual_commonjs_es_module_packages), so we'll have to support that.

In the meantime, you can do

```
import { mean } from "simple-statistics/dist/simple-statistics.mjs";
```

**Comment by tmcw** [comment]
Fixed in 7.0.9.

**Comment by ainthek** [comment]
tmcw. I Just uupdated package in node.js to 7.0.9 and still the same issue.
